### PR TITLE
Dev guide documentation

### PR DESCRIPTION
**Pull request by klemie**
Please look through `/documentation/developer-guide.md` 

pog thanks

### CODE REVIEW

**Comment by klemie** [comment]
[Full stack skill dev](https://trello.com/c/1rBx10y0/49-full-stack-skill-dev)

**Review by PokeyOne — COMMENTED** [review]
Looks generally good to me.

Only question is, are the `Components.d.ts` and `DataUpload.tsx` files related to this PR at all, or are they just along for the ride for reference or fun or something?

**Comment by PokeyOne** [comment]
Also there are merge conflicts with DataUpload aparently.

**Comment by PokeyOne** [comment]
Looks like those files are also already in the onboarding tutorial, so might want to just remove them from here?

**Pull request merged**
